// Base de alimentos comuns pra calculadora de calorias. Nomes do jeito que as
// pessoas realmente falam no dia a dia (não em termos de tabela nutricionista).
// Valores aproximados (fonte: tabelas nutricionais públicas tipo TACO) por
// porção usual — quando o alimento não estiver aqui, o usuário digita o nome
// que quiser e informa as calorias na mão.
const ALIMENTOS = [
  // Carboidratos e básicos
  { nome: 'Arroz branco', categoria: 'carboidratos', porcao: '100 g (1 escumadeira)', calorias: 128 },
  { nome: 'Arroz integral', categoria: 'carboidratos', porcao: '100 g (1 escumadeira)', calorias: 124 },
  { nome: 'Feijão', categoria: 'carboidratos', porcao: '100 g (1 concha)', calorias: 76 },
  { nome: 'Feijão preto', categoria: 'carboidratos', porcao: '100 g (1 concha)', calorias: 77 },
  { nome: 'Lentilha', categoria: 'carboidratos', porcao: '100 g', calorias: 93 },
  { nome: 'Grão de bico', categoria: 'carboidratos', porcao: '100 g', calorias: 121 },
  { nome: 'Pão francês', categoria: 'carboidratos', porcao: '1 unidade', calorias: 150 },
  { nome: 'Pão de forma', categoria: 'carboidratos', porcao: '1 fatia', calorias: 67 },
  { nome: 'Pão integral', categoria: 'carboidratos', porcao: '1 fatia', calorias: 65 },
  { nome: 'Pão de queijo', categoria: 'carboidratos', porcao: '1 unidade', calorias: 100 },
  { nome: 'Torrada', categoria: 'carboidratos', porcao: '1 unidade', calorias: 40 },
  { nome: 'Macarrão', categoria: 'carboidratos', porcao: '100 g', calorias: 158 },
  { nome: 'Batata', categoria: 'carboidratos', porcao: '100 g', calorias: 52 },
  { nome: 'Purê de batata', categoria: 'carboidratos', porcao: '100 g', calorias: 90 },
  { nome: 'Batata doce', categoria: 'carboidratos', porcao: '100 g', calorias: 77 },
  { nome: 'Mandioca', categoria: 'carboidratos', porcao: '100 g', calorias: 125 },
  { nome: 'Aveia', categoria: 'carboidratos', porcao: '2 colheres de sopa', calorias: 117 },
  { nome: 'Granola', categoria: 'carboidratos', porcao: '30 g', calorias: 150 },
  { nome: 'Tapioca', categoria: 'carboidratos', porcao: '1 unidade média', calorias: 89 },
  { nome: 'Milho', categoria: 'carboidratos', porcao: '100 g', calorias: 98 },
  { nome: 'Cuscuz', categoria: 'carboidratos', porcao: '100 g', calorias: 112 },

  // Proteínas
  { nome: 'Frango grelhado', categoria: 'proteinas', porcao: '100 g', calorias: 159 },
  { nome: 'Frango (coxa ou sobrecoxa)', categoria: 'proteinas', porcao: '100 g', calorias: 215 },
  { nome: 'Frango frito ou empanado', categoria: 'proteinas', porcao: '100 g', calorias: 250 },
  { nome: 'Carne moída', categoria: 'proteinas', porcao: '100 g', calorias: 212 },
  { nome: 'Bife', categoria: 'proteinas', porcao: '100 g', calorias: 219 },
  { nome: 'Carne de panela', categoria: 'proteinas', porcao: '100 g', calorias: 250 },
  { nome: 'Bacon', categoria: 'proteinas', porcao: '2 fatias', calorias: 160 },
  { nome: 'Ovo cozido', categoria: 'proteinas', porcao: '1 unidade', calorias: 78 },
  { nome: 'Ovo frito', categoria: 'proteinas', porcao: '1 unidade', calorias: 90 },
  { nome: 'Omelete', categoria: 'proteinas', porcao: '2 ovos', calorias: 154 },
  { nome: 'Peixe', categoria: 'proteinas', porcao: '100 g', calorias: 128 },
  { nome: 'Salmão', categoria: 'proteinas', porcao: '100 g', calorias: 208 },
  { nome: 'Atum (lata)', categoria: 'proteinas', porcao: '100 g', calorias: 116 },
  { nome: 'Camarão', categoria: 'proteinas', porcao: '100 g', calorias: 90 },
  { nome: 'Carne de porco', categoria: 'proteinas', porcao: '100 g', calorias: 210 },
  { nome: 'Linguiça', categoria: 'proteinas', porcao: '100 g', calorias: 296 },
  { nome: 'Salsicha', categoria: 'proteinas', porcao: '1 unidade', calorias: 150 },
  { nome: 'Presunto', categoria: 'proteinas', porcao: '1 fatia', calorias: 40 },
  { nome: 'Peito de peru', categoria: 'proteinas', porcao: '1 fatia', calorias: 30 },
  { nome: 'Tofu', categoria: 'proteinas', porcao: '100 g', calorias: 76 },

  // Laticínios
  { nome: 'Leite integral', categoria: 'laticinios', porcao: '1 copo (200 ml)', calorias: 122 },
  { nome: 'Leite desnatado', categoria: 'laticinios', porcao: '1 copo (200 ml)', calorias: 70 },
  { nome: 'Leite achocolatado', categoria: 'laticinios', porcao: '1 copo (200 ml)', calorias: 180 },
  { nome: 'Iogurte natural', categoria: 'laticinios', porcao: '1 pote (170 g)', calorias: 107 },
  { nome: 'Iogurte grego', categoria: 'laticinios', porcao: '100 g', calorias: 97 },
  { nome: 'Iogurte de frutas', categoria: 'laticinios', porcao: '1 pote (170 g)', calorias: 130 },
  { nome: 'Queijo minas', categoria: 'laticinios', porcao: '1 fatia', calorias: 72 },
  { nome: 'Queijo mussarela', categoria: 'laticinios', porcao: '1 fatia', calorias: 90 },
  { nome: 'Queijo prato', categoria: 'laticinios', porcao: '1 fatia', calorias: 80 },
  { nome: 'Requeijão', categoria: 'laticinios', porcao: '1 colher de sopa', calorias: 58 },
  { nome: 'Cream cheese', categoria: 'laticinios', porcao: '1 colher de sopa', calorias: 50 },
  { nome: 'Whey protein', categoria: 'laticinios', porcao: '1 scoop (30 g)', calorias: 120 },

  // Frutas
  { nome: 'Banana', categoria: 'frutas', porcao: '1 unidade', calorias: 63 },
  { nome: 'Maçã', categoria: 'frutas', porcao: '1 unidade', calorias: 68 },
  { nome: 'Laranja', categoria: 'frutas', porcao: '1 unidade', calorias: 65 },
  { nome: 'Mamão', categoria: 'frutas', porcao: '100 g', calorias: 40 },
  { nome: 'Abacate', categoria: 'frutas', porcao: '100 g', calorias: 96 },
  { nome: 'Manga', categoria: 'frutas', porcao: '1 unidade', calorias: 120 },
  { nome: 'Uva', categoria: 'frutas', porcao: '100 g', calorias: 53 },
  { nome: 'Morango', categoria: 'frutas', porcao: '100 g', calorias: 30 },
  { nome: 'Melancia', categoria: 'frutas', porcao: '100 g', calorias: 33 },
  { nome: 'Melão', categoria: 'frutas', porcao: '100 g', calorias: 29 },
  { nome: 'Abacaxi', categoria: 'frutas', porcao: '100 g', calorias: 48 },
  { nome: 'Pera', categoria: 'frutas', porcao: '1 unidade', calorias: 60 },
  { nome: 'Kiwi', categoria: 'frutas', porcao: '1 unidade', calorias: 42 },

  // Vegetais e legumes
  { nome: 'Alface', categoria: 'vegetais', porcao: '50 g', calorias: 7 },
  { nome: 'Brócolis', categoria: 'vegetais', porcao: '100 g', calorias: 25 },
  { nome: 'Cenoura', categoria: 'vegetais', porcao: '100 g', calorias: 34 },
  { nome: 'Tomate', categoria: 'vegetais', porcao: '100 g', calorias: 18 },
  { nome: 'Pepino', categoria: 'vegetais', porcao: '100 g', calorias: 12 },
  { nome: 'Cebola', categoria: 'vegetais', porcao: '50 g', calorias: 20 },
  { nome: 'Abobrinha', categoria: 'vegetais', porcao: '100 g', calorias: 20 },
  { nome: 'Couve', categoria: 'vegetais', porcao: '100 g', calorias: 39 },
  { nome: 'Repolho', categoria: 'vegetais', porcao: '100 g', calorias: 23 },
  { nome: 'Chuchu', categoria: 'vegetais', porcao: '100 g', calorias: 19 },
  { nome: 'Beterraba', categoria: 'vegetais', porcao: '100 g', calorias: 32 },

  // Gorduras e oleaginosas
  { nome: 'Azeite', categoria: 'gorduras', porcao: '1 colher de sopa', calorias: 119 },
  { nome: 'Óleo de cozinha', categoria: 'gorduras', porcao: '1 colher de sopa', calorias: 124 },
  { nome: 'Castanha do Pará', categoria: 'gorduras', porcao: '3 unidades', calorias: 132 },
  { nome: 'Amendoim', categoria: 'gorduras', porcao: '30 g', calorias: 170 },
  { nome: 'Amêndoas', categoria: 'gorduras', porcao: '20 g', calorias: 116 },
  { nome: 'Manteiga', categoria: 'gorduras', porcao: '10 g', calorias: 72 },
  { nome: 'Pasta de amendoim', categoria: 'gorduras', porcao: '1 colher de sopa', calorias: 120 },

  // Bebidas
  { nome: 'Café', categoria: 'bebidas', porcao: '1 xícara (100 ml)', calorias: 2 },
  { nome: 'Chá', categoria: 'bebidas', porcao: '1 xícara (200 ml)', calorias: 2 },
  { nome: 'Suco natural', categoria: 'bebidas', porcao: '1 copo (200 ml)', calorias: 90 },
  { nome: 'Vitamina de frutas', categoria: 'bebidas', porcao: '1 copo (300 ml)', calorias: 220 },
  { nome: 'Refrigerante', categoria: 'bebidas', porcao: '1 lata (350 ml)', calorias: 140 },
  { nome: 'Cerveja', categoria: 'bebidas', porcao: '1 lata (350 ml)', calorias: 150 },
  { nome: 'Vinho', categoria: 'bebidas', porcao: '1 taça (150 ml)', calorias: 125 },
  { nome: 'Água de coco', categoria: 'bebidas', porcao: '1 copo (200 ml)', calorias: 38 },
  { nome: 'Energético', categoria: 'bebidas', porcao: '1 lata (250 ml)', calorias: 115 },

  // Doces, lanches e pratos prontos
  { nome: 'Chocolate', categoria: 'doces', porcao: '1 barra pequena (25 g)', calorias: 135 },
  { nome: 'Bolo', categoria: 'doces', porcao: '1 fatia', calorias: 180 },
  { nome: 'Biscoito recheado', categoria: 'doces', porcao: '3 unidades', calorias: 145 },
  { nome: 'Biscoito água e sal', categoria: 'doces', porcao: '6 unidades', calorias: 100 },
  { nome: 'Sorvete', categoria: 'doces', porcao: '1 bola (100 g)', calorias: 207 },
  { nome: 'Milkshake', categoria: 'doces', porcao: '1 copo (300 ml)', calorias: 350 },
  { nome: 'Brigadeiro', categoria: 'doces', porcao: '1 unidade', calorias: 100 },
  { nome: 'Pudim', categoria: 'doces', porcao: '1 fatia', calorias: 200 },
  { nome: 'Pão de mel', categoria: 'doces', porcao: '1 unidade', calorias: 150 },
  { nome: 'Barra de cereal', categoria: 'doces', porcao: '1 unidade', calorias: 100 },
  { nome: 'Barra de proteína', categoria: 'doces', porcao: '1 unidade', calorias: 200 },
  { nome: 'Salgadinho de pacote', categoria: 'doces', porcao: '1 pacote pequeno (30 g)', calorias: 160 },
  { nome: 'Pipoca', categoria: 'doces', porcao: '1 saco pequeno (30 g)', calorias: 110 },
  { nome: 'Açaí na tigela', categoria: 'doces', porcao: '1 tigela (300 ml)', calorias: 300 },
  { nome: 'Pizza', categoria: 'doces', porcao: '1 fatia', calorias: 266 },
  { nome: 'Hambúrguer', categoria: 'doces', porcao: '1 lanche completo', calorias: 430 },
  { nome: 'Cachorro-quente', categoria: 'doces', porcao: '1 unidade', calorias: 300 },
  { nome: 'Batata frita', categoria: 'doces', porcao: '1 porção pequena', calorias: 310 },
  { nome: 'Nuggets', categoria: 'doces', porcao: '6 unidades', calorias: 250 },
  { nome: 'Coxinha', categoria: 'doces', porcao: '1 unidade', calorias: 250 },
  { nome: 'Pastel', categoria: 'doces', porcao: '1 unidade', calorias: 300 },
  { nome: 'Esfirra', categoria: 'doces', porcao: '1 unidade', calorias: 200 },
  { nome: 'Empada', categoria: 'doces', porcao: '1 unidade', calorias: 220 },
  { nome: 'Salgado assado (geral)', categoria: 'doces', porcao: '1 unidade', calorias: 180 },
  { nome: 'Esfiha', categoria: 'doces', porcao: '1 unidade', calorias: 200 },
  { nome: 'Sushi/combinado', categoria: 'doces', porcao: '10 peças', calorias: 300 },
  { nome: 'Lasanha', categoria: 'doces', porcao: '1 fatia', calorias: 350 },
  { nome: 'Strogonoff', categoria: 'doces', porcao: '1 prato (200 g)', calorias: 350 },
  { nome: 'Feijoada', categoria: 'doces', porcao: '1 prato (300 g)', calorias: 400 },
  { nome: 'Paçoca', categoria: 'doces', porcao: '1 unidade', calorias: 90 }
];
